fieldLayouts:
  00aaad6e-2347-4228-8894-eefa5c193964:
    tabs:
      -
        elements:
          -
            fieldUid: 064b3f56-33de-4c92-9eeb-779375f842be
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: home
hasTitleField: false
name: Home
section: d306a14d-ae05-490d-b4fa-a8fa73016887
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
